name: Deploy to production

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Prepare docker
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: cavers-fe:lastest
        output: type=docker
